grid/urls.py
from django.conf.urls import url

from . import views

app_name = 'grid'

urlpatterns = [
        # list
        url(r'^$', views.ListListView.as_view(), name='home'),
        url(r'^contacts/(?P<lists_id>[-\w]+)/$', views.PersonListView.as_view(), name='list_detail'),
        url(r'^templates/$', views.TemplateListView.as_view(), name='template_list'),

        # detail
        url(r'^contact/(?P<slug>[-\w]+)$', views.PersonDetailView.as_view(), name='people_detail'),
        url(r'^template/(?P<slug>[-\w]+)/$', views.TemplateDetailView.as_view(), name='template_detail'),

        # create
        url(r'^add/$', views.ListCreateView.as_view(), name='list_create'),
        url(r'^add/contact/$', views.PersonCreateView.as_view(), name='people_create'),
        url(r'^add/template/$', views.TemplateCreateView.as_view(), name='template_create'),

        # edit
        url(r'^edit/(?P<slug>[-\w]+)/$', views.ListUpdateView.as_view(), name='list_edit'),
        url(r'^edit/contact/(?P<slug>[-\w]+)/$', views.PersonUpdateView.as_view(), name='people_edit'),
        url(r'^edit/template/(?P<slug>[-\w]+)/$', views.TemplateUpdateView.as_view(), name='template_edit'),

        # delete
        url(r'^delete/contact/(?P<pk>[-\w]+)/$', views.PersonRemoveView.as_view(), name='people_delete'),

        # send email
        url(r'^send/(?P<tp_pk>[-\w]+)/(?P<to_pk>[-\w]+)/$', views.SendEmailView.as_view(), name='send_email'),
        url(r'^email/$', views.CustomEmailView.as_view(), name='custom_email'),
        ]

jademail/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import LoginView, LogoutView

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^logout/$', LogoutView.as_view(), name='logout'),
        url(r'^login/$', LoginView.as_view(), name='login'),
        url(r'^', include('grid.urls')),
        ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grid/forms.py
from __future__ import absolute_import
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from django import forms
from ckeditor.widgets import CKEditorWidget

from . import models


class EmailForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    subject = forms.CharField()
    template = forms.ModelChoiceField(queryset=models.Template.objects.all())
    content = forms.CharField(widget=CKEditorWidget())
    attachment = forms.FileField(required=False)

    class Meta:
        fields = ('name', 'email', 'subject', 'template', 'content', 'attachment')
        fields_required = ['name', 'email', 'content', 'template', 'subject']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(EmailForm, self).__init__(*args, **kwargs)
        self.fields['template'].queryset = models.Template.objects.filter(
                    user=self.request.user)
        self.helper = FormHelper()
        self.helper.form_class = 'col-md-9 col-md-offset-1'
        self.helper.layout = Layout(
            'name',
            'email',
            'subject',
            'template',
            'attachment',
            'content',
            ButtonHolder(
                Submit('send', 'Send', css_class='btn btn-block btn-default')
                )
            )


class ListForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'template', 'description')
        model = models.List

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(ListForm, self).__init__(*args, **kwargs)
        self.fields['template'].queryset = models.Template.objects.filter(
                    user=self.request.user)
        self.helper = FormHelper()
        self.helper.form_class = 'col-md-9 col-md-offset-1'
        self.helper.layout = Layout(
            'title',
            'template',
            'description',
            ButtonHolder(
                Submit('send', 'Send', css_class='btn btn-block btn-default')
                )
            )


class PersonForm(forms.ModelForm):
    class Meta:
        fields = ('name', 'last_name', 'email', 'mobile', 'web', 'linked_in',
                  'facebook', 'lists_id', 'street')
        model = models.Person

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(PersonForm, self).__init__(*args, **kwargs)
        self.fields['lists_id'].queryset = models.List.objects.filter(
                    user=self.request.user)
        self.helper = FormHelper()
        self.helper.form_class = 'col-md-9 col-md-offset-1'
        self.helper.layout = Layout(
            'name',
            'last_name',
            'email',
            'mobile',
            'web',
            'linked_in',
            'facebook',
            'lists_id',
            'street',
            ButtonHolder(
                Submit('send', 'Send', css_class='btn btn-block btn-default')
                )
            )


class TemplateForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'content', 'template_file', 'attachment')
        model = models.Template

    def __init__(self, *args, **kwargs):
        super(TemplateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'col-md-9 col-md-offset-1'
        self.helper.layout = Layout(
            'title',
            'template_file',
            'attachment',
            'content',
            ButtonHolder(
                Submit('send', 'Send', css_class='btn btn-block btn-default')
                )
            )


class CommentForm(forms.ModelForm):
    class Meta:
        fields = ('title', 'content', 'person_id')
        model = models.Comment

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'col-md-9 col-md-offset-1'
        self.helper.layout = Layout(
            'title',
            'content',
            'person_id',
            ButtonHolder(
                Submit('send', 'Send', css_class='btn btn-block btn-default')
                )
            )

grid/views.py
import base64
import sendgrid
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import RedirectView
from django.http import Http404
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count
from django.contrib import messages
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from sendgrid.helpers.mail import Email, Content, Mail, Personalization, Attachment
from braces import views
from slugify import slugify

from .models import List
from .models import Person
from .models import Template

from . import forms


class RestrictToOwnerMixin(views.LoginRequiredMixin):
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class EmailParse():

    def render_body(self, to, path):
        f = open(path)
        body = ""

        for line in f:
            body += line.replace('{{TO}}', to)
        f.close()

        return body

    def attach_file(self, f, ext, slug, title):
        attachment = Attachment()
        attachment.set_content(base64.b64encode(f.read()))
        attachment.set_type("application/"+ext)
        attachment.set_filename(slug+"."+ext)
        attachment.set_disposition("attachment")
        attachment.set_content_id(title)

        return attachment


class SendEmailView(
        views.LoginRequiredMixin,
        EmailParse,
        RedirectView):

    model = Template

    def __init__(self, **kwargs):
        self.sg = sendgrid.SendGridAPIClient(apikey=settings.SENDGRID_API_KEY)

        for key, value in kwargs.items():
            setattr(self, key, value)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('grid:people_detail',
                kwargs={'slug': self.person.slug}) + "?q=" + kwargs.get('tp_pk')

    def get_object(self, tp_pk):
        try:
            template = self.model.objects.get(
                    lists__slug=tp_pk,
                    user=self.request.user
                    )
        except Template.DoesNotExist:
            raise Http404
        else:
            return template

    def get_person(self, to_pk, tp_pk):
        try:
            person = Person.objects.get(
                    pk=to_pk,
                    lists_id__slug=tp_pk,
                    user=self.request.user
                    )
        except Person.DoesNotExist:
            raise Http404
        else:
            return person

    def get(self, request, *args, **kwargs):
        self.template = self.get_object(kwargs.get('tp_pk'))
        self.person = self.get_person(kwargs.get('to_pk'), kwargs.get('tp_pk'))

        mail = Mail()
        mail.set_from(Email(self.request.user.email))
        mail.set_subject(self.template.title)

        personalization = Personalization()
        personalization.add_to(Email(self.person.email))
        mail.add_personalization(personalization)

        body = self.render_body(self.person.name, self.template.template_email.path)
        mail.add_content(Content("text/html", body))

        if self.template.attachment:
            path = self.template.attachment.path
            ext = path.split('.')[-1]
            with open(path, "rb") as f:
                mail.add_attachment(self.attach_file(
                    f, ext, self.template.slug, self.template.title))

        self.sg.client.mail.send.post(request_body=mail.get())
        messages.info(
            request,
            """You have just send an email to <strong>{0.email}</strong>
            with the subject <strong>{1}</strong>
            """
            .format(self.person, self.template.title))

        self.person.email_sent = True
        self.person.save()

        return super(SendEmailView, self).get(request, *args, **kwargs)


class ListListView(
        RestrictToOwnerMixin,
        views.SetHeadlineMixin,
        ListView):

    model = List
    headline = 'Lists'
    paginate_by = 25

    def get_queryset(self):
        queryset = super(ListListView, self).get_queryset()
        queryset = queryset.annotate(contact_count=Count('contacts'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(ListListView, self).get_context_data(*args, **kwargs)
        context['path'] = reverse_lazy('grid:list_create')
        context['active_tab'] = 'list'
        return context


class ListCreateView(
        views.LoginRequiredMixin,
        views.SetHeadlineMixin,
        views.FormMessagesMixin,
        CreateView):

    headline = 'Create a new list'
    form_class = forms.ListForm
    model = List
    form_invalid_message = _(u'There was an error in the process')

    def get_form_kwargs(self):
        kwargs = super(ListCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_form_valid_message(self):
        return u"""You have just <strong>{0}</strong> the list
               <strong>{1.title}</strong> successfully
               """.format(self.headline, self.object)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(ListCreateView, self).form_valid(form)


class ListUpdateView(
        RestrictToOwnerMixin,
        views.SetHeadlineMixin,
        views.FormMessagesMixin,
        UpdateView):

    headline = 'Edit'
    form_class = forms.ListForm
    model = List
    form_invalid_message = _(u'There was an error in the process')

    def get_form_valid_message(self):
        return u"""You have just <strong>{0}</strong> the list
               <strong>{1.title}</strong> successfully
               """.format(self.headline, self.object)

    def get_form_kwargs(self):
        kwargs = super(ListUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class PersonRemoveView(
        views.LoginRequiredMixin,
        RedirectView):

    model = Person

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('grid:home')

    def get_object(self, pk, lists_pk):
        try:
            person = self.model.objects.get(
                    pk=pk,
                    user=self.request.user
                    )
        except Person.DoesNotExist:
            raise Http404
        else:
            return person

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(kwargs.get('pk'), kwargs.get('lists_pk'))
        self.list = self.object.lists_id
        messages.warning(
                request,
                """
                The contact <strong>{0.email}</strong> was removed from
                your contacts
                """.format(self.object))
        self.object.delete()
        return super(PersonRemoveView, self).get(request, *args, **kwargs)


class PersonListView(
        RestrictToOwnerMixin,
        views.SetHeadlineMixin,
        ListView):

    model = Person
    paginate_by = 25
    headline = 'Contacts from'

    def get_queryset(self):
        queryset = super(PersonListView, self).get_queryset()
        queryset = queryset.filter(lists_id__slug=self.kwargs['lists_id'])
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(PersonListView, self).get_context_data(*args, **kwargs)
        context['list_slug'] = self.kwargs['lists_id']
        context['path'] = reverse_lazy('grid:people_create')
        return context


class PersonDetailView(
        RestrictToOwnerMixin,
        DetailView):

    model = Person

    def get_context_data(self, *args, **kwargs):
        context = super(PersonDetailView, self).get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context


class PersonCreateView(
        views.LoginRequiredMixin,
        views.SetHeadlineMixin,
        views.FormMessagesMixin,
        CreateView):

    headline = 'Create a new contact'
    form_class = forms.PersonForm
    model = Person
    form_invalid_message = _(u'There was an error in the process')

    def get_form_valid_message(self):
        return u"""You have just <strong>{0}</strong> the contact
               <strong>{1.email}</strong> successfully
               """.format(self.headline, self.object)

    def get_form_kwargs(self):
        kwargs = super(PersonCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(PersonCreateView, self).form_valid(form)


class PersonUpdateView(
        RestrictToOwnerMixin,
        views.SetHeadlineMixin,
        views.FormMessagesMixin,
        UpdateView):

    headline = 'Edit'
    form_class = forms.PersonForm
    model = Person
    form_invalid_message = _(u'There was an error in the process')

    def get_form_valid_message(self):
        return u"""You have just <strong>{0}</strong> the contact
               <strong>{1.email}</strong> successfully
               """.format(self.headline, self.object)

    def get_form_kwargs(self):
        kwargs = super(PersonUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class TemplateListView(
        RestrictToOwnerMixin,
        views.SetHeadlineMixin,
        ListView):

    model = Template
    paginate_by = 25
    headline = 'Templates'

    def get_context_data(self, *args, **kwargs):
        context = super(TemplateListView, self).get_context_data(*args, **kwargs)
        context['path'] = reverse_lazy('grid:template_create')
        context['active_tab'] = 'template'
        return context

grid/templates/grid/list_form.html
{% extends "_layouts/base.html"  %}
{% load crispy_forms_tags %}

{% block content %}
{% crispy form %}
{% endblock %}

grid/templates/grid/list_list.html
{% extends "_layouts/base.html"  %}

{% block content %}
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Template</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td class="col-md-5">
        <a href="{{ object.get_absolute_url }}">
          <strong>
            {{ object.title | title }}
            <span class="badge">
              {{ object.contact_count }}
            </span>
          </strong>
        </a>
      </td>
      <td class="col-md-4">
        <a href="{{ object.template.get_absolute_url }}">
        {{ object.template }}
        </a>
      </td>
      <td class="col-md-3">
        <a href="{{ object.get_absolute_url }}" class="btn btn-primary glyphicon glyphicon-eye-open"></a>
        <a href="{% url 'grid:list_edit' object.slug %}" class="btn btn-default glyphicon glyphicon-pencil"></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

grid/templates/grid/person_detail.html
{% extends "_layouts/base.html"  %}

{% block content %}
<div class="panel panel-default">

  <div class="panel-heading">
    <h2>
      {{ object.name | title }}
      {% if object.last_name %}
      {{ object.last_name | title }}
      {% endif %}
    </h2>
  </div>
  <div class="panel-body">
    <strong>Email: </strong>{{ object.email }}
    {% if object.email_sent %}
    <span class="label label-success">{{ 'Send'|upper }}</span>
    {% else %}
    <span class="label label-danger">{{ 'Not send'|upper }}</span>
    {% endif %}
    <div class="pull-right">
      <a href="{% url 'grid:people_edit' object.slug %}" class="btn btn-default glyphicon glyphicon-pencil"></a>
      {% if q %}
      <a href="{% url 'grid:send_email' q object.pk %}" class="btn btn-primary glyphicon glyphicon-send"> Send email</a>
      {% endif %}
    </div>
  </div>
  <div class="panel-body">
    <strong>Web: </strong>{{ object.web }}
  </div>
  <div class="panel-body">
    <strong>Mobile: </strong>{{ object.mobile }}
  </div>
  <div class="panel-body">
    <strong>Linkedin: </strong>{{ object.linked_in }}
  </div>
  <div class="panel-body">
    <strong>Facebook: </strong>{{ object.facebook }}
  </div>
  <div class="panel-body">
    <strong>Address: </strong>{{ object.street }}
  </div>
  <div class="panel-body">
    <strong>Lists: </strong>
    {% for list in object.lists_id.all %}
    {{ list.title }}, 
    {% endfor %}
  </div>
</div>
<div class=" pull-right">
  <a href="{% url 'grid:people_delete' object.pk %}" class="btn btn-danger glyphicon glyphicon-trash"></a>
</div>
{% endblock %}

grid/templates/grid/person_form.html
{% extends "_layouts/base.html"  %}
{% load crispy_forms_tags %}

{% block content %}
{% crispy form %}
{% endblock %}

grid/templates/grid/person_list.html
{% extends "_layouts/base.html"  %}

{% block content %}
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Send</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td class="col-md-4">
        <a href="{{ object.get_absolute_url }}?q={{ list_slug }}">
          <strong>
            {% if object.last_name %}
            {{ object.last_name }}, 
            {% endif %}
            {{ object.name | title }}
          </strong>
        </a>
      </td>
      <td class="col-md-1">
        <i class="{% if object.email_sent %}
        alert-success glyphicon glyphicon-ok-sign
            {% else %}
        alert-danger glyphicon glyphicon-remove-sign
            {% endif %}"></i>
      </td>
      <td class="col-md-4">
        <a href="{{ object.get_absolute_url }}?q={{ list_slug }}">
        {{ object.email }}
        </a>
      </td>
      <td class="col-md-3">
        <a href="{{ object.get_absolute_url }}?q={{ list_slug }}" class="btn btn-primary glyphicon glyphicon-eye-open"></a>
        <a href="{% url 'grid:people_edit' object.slug %}" class="btn btn-default glyphicon glyphicon-pencil"></a>
        <a href="{% url 'grid:people_delete' object.pk %}" class="btn btn-danger glyphicon glyphicon-trash"></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

grid/templates/grid/template_detail.html
{% extends "_layouts/base.html"  %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>
      {{ object.title | title }}
      {% if object.last_name %}
      {{ object.last_name | title }}
      {% endif %}
    </h2>
    <div class="pull-right">
      <a href="{% url 'grid:template_edit' object.slug %}" class="btn btn-default glyphicon glyphicon-pencil"></a>
    </div>
  </div>
  <div class="panel-body">
    <strong>Content: </strong>{{ object.content | safe }}
  </div>
  {% if object.attachment %}
  <div class="panel-body">
    <strong>Attachment: </strong><a href="{{ object.attachment.url }}">{{ object.attachment.url }}</a>
  </div>
  {% endif %}
  <div class="panel-body">
    <strong>Template: </strong><a href="{{ object.template_file.url }}">{{ object.template_file.url }}</a>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Demo</h3>
  </div>
  <div class="panel-body">
    <iframe src="{{ object.template_email.url }}"  width="100%" height="680" frameBorder="0"></iframe>
  </div>
</div>
{% endblock %}

grid/templates/grid/template_form.html
{% extends "_layouts/base.html"  %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
{% crispy form %}
{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
{% endblock %}

grid/templates/grid/template_list.html
{% extends "_layouts/base.html"  %}

{% block content %}
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Template</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <td class="col-md-5">
        <a href="{{ object.get_absolute_url }}">
          <strong>
            {{ object.title | title }}
            <span class="badge">
              {{ object.list_count }}
            </span>
          </strong>
        </a>
      </td>
      <td class="col-md-4">
        <a href="{{ object.template_email.url }}">
        {{ object.template_email }}
        </a>
      </td>
      <td class="col-md-3">
        <a href="{{ object.get_absolute_url }}" class="btn btn-primary glyphicon glyphicon-eye-open"></a>
        <a href="{% url 'grid:template_edit' object.slug %}" class="btn btn-default glyphicon glyphicon-pencil"></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}