grid/urls.py
from django.conf.urls import url

from . import views

app_name = 'grid'

urlpatterns = [
        # list
        url(r'^$', views.ListListView.as_view(), name='home'),
        url(r'^contacts/(?P<lists_id>[-\w]+)/$', views.PersonListView.as_view(), name='list_detail'),
        url(r'^templates/$', views.TemplateListView.as_view(), name='template_list'),

        # detail
        url(r'^contact/(?P<slug>[-\w]+)$', views.PersonDetailView.as_view(), name='people_detail'),
        url(r'^template/(?P<slug>[-\w]+)/$', views.TemplateDetailView.as_view(), name='template_detail'),

        # create
        url(r'^add/$', views.ListCreateView.as_view(), name='list_create'),
        url(r'^add/contact/$', views.PersonCreateView.as_view(), name='people_create'),
        url(r'^add/template/$', views.TemplateCreateView.as_view(), name='template_create'),

        # edit
        url(r'^edit/(?P<slug>[-\w]+)/$', views.ListUpdateView.as_view(), name='list_edit'),
        url(r'^edit/contact/(?P<slug>[-\w]+)/$', views.PersonUpdateView.as_view(), name='people_edit'),
        url(r'^edit/template/(?P<slug>[-\w]+)/$', views.TemplateUpdateView.as_view(), name='template_edit'),

        # delete
        url(r'^delete/contact/(?P<pk>[-\w]+)/$', views.PersonRemoveView.as_view(), name='people_delete'),

        # send email
        url(r'^send/(?P<tp_pk>[-\w]+)/(?P<to_pk>[-\w]+)/$', views.SendEmailView.as_view(), name='send_email'),
        url(r'^email/$', views.CustomEmailView.as_view(), name='custom_email'),
        ]

jademail/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import LoginView, LogoutView

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^logout/$', LogoutView.as_view(), name='logout'),
        url(r'^login/$', LoginView.as_view(), name='login'),
        url(r'^', include('grid.urls')),
        ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_modules/messages.html
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}"{% endif %}>{{ message|safe }}</div>
{% endfor %}
{% endif %}

templates/_modules/nav.html
<div id="navbar" class="navbar navbar-inverse" style="margin-bottom:0px!important; border-radius:0!important">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'grid:home' %}">JadeMail</a>
    </div>
    {% if user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
      <li class="{% if active_tab == 'list' %}active{% endif %}"><a href="{% url 'grid:home' %}">Lists</a></li>
      <li class="{% if active_tab == 'template' %}active{% endif %}"><a href="{% url 'grid:template_list' %}">Templates</a></li>
      <li class="{% if active_tab == 'email' %}active{% endif %}"><a href="{% url 'grid:custom_email' %}">Send Email</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </ul>
    {% endif %}
  </div>
</div>
<div style="background:#00A86B!important;color:white!important;" class="jumbotron text-center">
  <div class="container">
    <h1>{{ headline }} {{ list_slug|title }}{{ object.name }}{{ object.title }}</h1>
  </div>
  {% if user.is_authenticated and not object and not form and active_tab != 'email'%}
  <div style="margin:3em auto 0 auto;width:50px;height:50px;border: 3px dashed;border-radius: 50%;">
    <a href="{{ path }}" style="color:white!important; with:100%; height:100%;">
      <i class="glyphicon glyphicon-plus" style="margin-top: 25%;font-size: 1.3em;"></i>
    </a>
  </div>
  {% endif %}
</div>